apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ include "agent.namespace" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.agent.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
