{{- if .Values.desktop.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "desktop.fullname" . }}-home
  namespace: {{ include "desktop.namespace" . }}
  labels:
    {{- include "desktop.labels" . | nindent 4 }}
  annotations:
    desktop.workstation.io/user: {{ .Values.desktop.userId }}
spec:
  accessModes:
    {{- toYaml .Values.desktop.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.desktop.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.desktop.persistence.size }}
{{- end }}
