apiVersion: v1
kind: Secret
metadata:
  name: {{ include "desktop.fullname" . }}-credentials
  namespace: {{ include "desktop.namespace" . }}
  labels:
    {{- include "desktop.labels" . | nindent 4 }}
type: Opaque
data:
  vnc-password: {{ include "desktop.vncPassword" . | b64enc | quote }}
