apiVersion: v1
kind: Service
metadata:
  name: {{ include "desktop.fullname" . }}
  namespace: {{ include "desktop.namespace" . }}
  labels:
    {{- include "desktop.labels" | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.desktop.vnc.port }}
      targetPort: vnc
      protocol: TCP
      name: vnc
    {{- if eq .Values.desktop.type "guacamole" }}
    - port: {{ .Values.desktop.guacamole.port }}
      targetPort: guacamole
      protocol: TCP
      name: guacamole
    {{- end }}
    {{- if eq .Values.desktop.type "novnc" }}
    - port: 6080
      targetPort: novnc
      protocol: TCP
      name: novnc
    {{- end }}
  selector:
    {{- include "desktop.selectorLabels" | nindent 4 }}
