apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloud-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "workstation.labels" . | nindent 4 }}
type: Opaque
data: {}
  # AWS_ACCESS_KEY_ID: <base64>
  # AWS_SECRET_ACCESS_KEY: <base64>
  # AZURE_CLIENT_ID: <base64>
  # AZURE_CLIENT_SECRET: <base64>
  # AZURE_TENANT_ID: <base64>
  # AZURE_SUBSCRIPTION_ID: <base64>
  # HETZNER_TOKEN: <base64>
---
{{- if .Values.services.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "workstation.labels" . | nindent 4 }}
type: Opaque
data: {}
  # POSTGRES_USER: <base64>
  # POSTGRES_PASSWORD: <base64>
{{- end }}
